spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 운영은 validate 권장
    show-sql: true

toss:
  payments:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}

file:
  storage:
    type: local
  upload:
    base-path: /home/gitlab-runner/uploads
    url-prefix: /uploads

logging:
  level:
    com.example.cinema: DEBUG