spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 운영은 validate 권장
    show-sql: true

file:
  upload:
    base-path: /home/gitlab-runner/uploads

logging:
  level:
    com.example.cinema: DEBUG